insert into Item (id, itemName, nameExt, datum, developer, description, type, profiel, plaatje, doc,  active) values(nextval('item_id_seq'), 'HTML5', 'markup language', '2014', 'W3C/WHATWG', 'Hyper Text Markup Language is WWWs core markup language', 'markup language',  'is a markup language used for structuring and presenting content on the World Wide Web. It is the fifth and current version of the HTML standard.', 'Images/HTML5.png', 'Images/HTML5.pdf', true );
insert into Item (id, itemName, nameExt, datum, developer, description, type, profiel, plaatje, doc,  active) values(nextval('item_id_seq'), 'CSS3', 'Style Sheet', '1996', 'W3C', 'Cascading Style Sheets ', 'style sheet language ',  'is a style sheet language used for describing the presentation of a document written in a markup language.', 'Images/CSS3.png', 'Images/CSS3.html', true );
insert into Item (id, itemName, nameExt, datum, developer, description, type, profiel, plaatje, doc,  active) values(nextval('item_id_seq'), 'JavaScript', 'Scripting language', '1995', 'Netscape Communications ', ' Alongside HTML and CSS, JavaScript is one of the three core technologies of World Wide Web content production', 'Scripting language', 'is a high­level, dynamic, untyped, and interpreted programming language. It has been standardized in the ECMAScript language specification.', 'Images/JavaScript.png', 'Images/JavaScript.pdf', true );
insert into Item (id, itemName, nameExt, datum, developer, description, type, profiel, plaatje, doc,  active) values(nextval('item_id_seq'), 'JSON', 'format', '2000', 'ECMA INTERNATIONAL', 'JavaScript Object Notation', 'data format.', 'is an open-standard format that uses human-readable text to transmit data objects consisting of attribute–value pairs. It is the most common data format used for asynchronous browser/server communication, largely replacing XML, and is used by AJAX.', 'Images/JSON.png', 'Images/JSON.pdf', true );
insert into Item (id, itemName, nameExt, datum, developer, description, type, profiel, plaatje, doc,  active) values(nextval('item_id_seq'), 'Ajax', ' a group of technologies ', '2005', 'W3C ', 'Asynchronous JavaScript+CSS+DOM+XMLHttpRequest', 'specification',  'a set of Web development techniques using many Web technologies on the client side to create asynchronous Web applications', 'Images/Ajax.png', 'Images/Ajax.pdf', true );

insert into Item (id, itemName, nameExt, datum, developer, description, type, profiel, plaatje, doc,  active) values(nextval('item_id_seq'), 'JAX-RS', 'web services ', '2008 ', 'Oracle ', 'Java API for RESTful Web Services', 'API',  'is a Java programming language API spec that provides support in creating web services according to the Representational State Transfer (REST) architectural pattern.', 'Images/JAX-RS.png', 'Images/JAX-RS.pdf', true );
insert into Item (id, itemName, nameExt, datum, developer, description, type, profiel, plaatje, doc,  active) values(nextval('item_id_seq'), 'JavaEE', 'computing platform', '1999', 'Oracle', 'Java Platform, Enterprise Edition', 'computing platform',  'is a widely used computing platform for development and deployment of enterprise software (network and web services). Java EE was formerly known as Java 2Platform, Enterprise Edition or J2EE.', 'Images/JavaEE.png', 'Images/JavaEE.html', true );
insert into Item (id, itemName, nameExt, datum, developer, description, type, profiel, plaatje, doc,  active) values(nextval('item_id_seq'), 'Java', 'programming language ', '1995', 'Oracle ', 'Java is a generalpurpose computer programming language', 'programming language',  'is a generalpurpose programming language that is concurrent, classbased, objectoriented, and specifically designed to have as few implementation dependencies as possible.', 'Images/Java.png', 'Images/Java.pdf', true );

insert into Item (id, itemName, nameExt, datum, developer, description, type, profiel, plaatje, doc,  active) values(nextval('item_id_seq'), 'JPA', 'specification', '2006', 'Oracle', 'Java Persistence API', 'API', 'is a Java application programming interface specification that describes the management of relational data in applications using Java Platform SE / EE', 'Images/JPA.png', 'Images/JPA.pdf', true );
insert into Item (id, itemName, nameExt, datum, developer, description, type, profiel, plaatje, doc,  active) values(nextval('item_id_seq'), 'DAO', 'abstract interface', '2000', 'Sun Microsystems, Inc', 'Data Access Object', 'interface',  'is an object that provides an abstract interface to some type of database or other persistence mechanism. By mapping application calls to the persistence layer, the DAO provides some specific data operations without exposing details of the database.', 'Images/DAO.png', 'Images/DAO.pdf', true );
insert into Item (id, itemName, nameExt, datum, developer, description, type, profiel, plaatje, doc,  active) values(nextval('item_id_seq'), 'Hibernate', 'ORM', '2001', 'Red Hat', 'Object-relational mapping tool', 'object-relational mapping', 'provides a framework for mapping an object-oriented domain model to a relational database. Hibernate solves object-relational impedance mismatch problems by replacing direct, persistent database accesses with high-level object handling functions.', 'Images/Hibernate.png', 'Images/Hibernate.pdf', true );
insert into Item (id, itemName, nameExt, datum, developer, description, type, profiel, plaatje, doc,  active) values(nextval('item_id_seq'), 'PostgreSql', 'database', '1996', 'PostgreSQL Global Development Group', 'Object-Relational DataBase', 'database',  'is an objectrelational database (ORDBMS) – i.e. an RDBMS, with additional "object" features', 'Images/PostgreSql.png', 'Images/PostgreSql.pdf', true );

insert into Item (id, itemName, nameExt, datum, developer, description, type, profiel, plaatje, doc,  active) values(nextval('item_id_seq'), 'WildFly', 'application server ', '1999', 'Red Hat (JBoss) ', 'WildFly (JBoss) application server ', 'application server',  'is written in Java, and implements the Java Platform, Enterprise Edition (Java EE) specification. It runs on multiple platforms.', 'Images/WildFly.png', 'Images/WildFly.pdf', true );
insert into Item (id, itemName, nameExt, datum, developer, description, type, profiel, plaatje, doc,  active) values(nextval('item_id_seq'), 'Eclipse', 'IDE', '2001', 'Eclipse Foundation', 'integrated development environment', 'IDE',  'is an integrated development environment (IDE) used in computer programming, and is the most widely used Java IDE.', 'Images/Eclipse.jpg', 'Images/Eclipse.html', true );
insert into Item (id, itemName, nameExt, datum, developer, description, type, profiel, plaatje, doc,  active) values(nextval('item_id_seq'), 'GitHub', 'version control repository', '2008', 'GitHub, Inc. ', 'Git repository hosting service', 'distributed version control', 'is a web-based Git or version control repository and Internet hosting service. It offers distributed version control and source code management functionality.', 'Images/GitHub.png', 'Images/GitHub.html', true );
insert into Item (id, itemName, nameExt, datum, developer, description, type, profiel, plaatje, doc,  active) values(nextval('item_id_seq'), 'Scrum', 'Agile', '1996', 'Ken Schwaber and Jeff Sutherland', 'Scrum is a general framework', 'A Management Framework',  'is a management framework for incremental product development using one or more cross-functional, self-organizing teams of about seven people each.', 'Images/Scrum.png', 'Images/Scrum.pdf', true );
insert into Item (id, itemName, nameExt, datum, developer, description, type, profiel, plaatje, doc,  active) values(nextval('item_id_seq'), 'Webtools', 'used', '2016', 'Training project', 'JavaEE based tools & techniques', 'Web Technologies',  'Quick reference to website tools used in the project', 'Images/Webtools.png', 'Images/Webtools.docx', true );

insert into Item (id, itemName, nameExt, datum, developer, description, type, profiel, plaatje, doc,  active) values(nextval('item_id_seq'), 'GreatGig', 'Pink Floyd', '1994', 'Pink Floyd', 'Live at Earls Court London', 'ref to video in folder', 'The Great Gig in the sky', 'Images/GreatGig.jpg', 'Images/GreatGig.mp4', true );
insert into Item (id, itemName, nameExt, datum, developer, description, type, profiel, plaatje, doc,  active) values(nextval('item_id_seq'), 'Never Never Never', 'Shirley Bassey', '1973', 'Shirley Bassey', 'Live at Royal Albert Hall',  'ref to html in folder refs to youtube', 'Never Never Never' , 'Images/Shirley.jpg' , 'Images/Shirley.html', true );
insert into Item (id, itemName, nameExt, datum, developer, description, type, profiel, plaatje, doc,  active) values(nextval('item_id_seq'), 'We Are the World', 'USA for Africa', '1985', 'Several artists', 'Live performance',  'ref to video in folder', 'USA for Africa (United Support of Artists for Africa) was the name under which forty-seven predominantly U.S. artists led by Michael Jackson and Lionel Richie recorded the hit single in 1985. This super group was inspired by Bob Geldofs Band Aid.' , 'Images/We Are the World.jpg'   , 'Images/We Are the World.mp4' , true );